language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

os:
  - linux
#  - osx

dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

addons:
  apt:
    update: true
    packages: ffmpeg
  homebrew:
    packages: ffmpeg

script:
  - py.test -v tests/
